[project]
name = "jwt-learn"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiobcrypt==3.2.0",
    "aiosqlite==0.21.0",
    "authx==1.4.2",
    "bcrypt==4.3.0",
    "fastapi>=0.115.12",
    "sqlalchemy==2.0.41",
    "uvicorn>=0.34.2",
]
